### PR TITLE
Added first aid for burns

### PR DESCRIPTION
**Pull request by jhimly**
@HeynSekk  I added some resources in the datacontext.txt file as mentioned in #7  .
Hope this helps!

### CODE REVIEW

**Comment by HeynSekk** [comment]
Thanks 😊 for adding a valuable first aid. I will merge your PR after watching the videos and webpages you provided. Those content would be helpful.

**Comment by HeynSekk** [comment]
I think it will be better to change the brief summary as the following because the brief summary also help users remember the first aid procedures just by spending a very short time on reading the summary words, when they forget what they learned. Brief summary is useful as a speedy reference to look back when forget.

Brief summary)
For minor burns,
- place burned area under cool water for at least 10 minutes 
- don't break blisters.
- if they do break, clean with mild soap and water and apply antibiotics ointments and cover it with a nonstick gauze bandage
- if a rash develops, stop using the ointment
- you may use moisturizer or aloe vera lotion to soothe the burn
- if blisters larger than little fingernails, see your doctor
- if pain, use over-the-counter pain relievers

Thanks for your contribution. I will merge your PR. 

This app will be better when you add more contents that are useful like this one you added. So your future contributions are very welcome 😊.

**Comment by jhimly** [comment]
Thank you so much for merging my PR.
And thanks for giving me an idea about how the brief summary should be framed.
I will add more content as and when I get.  I really like your project.

**Comment by HeynSekk** [comment]
I'm glad to see someone like you, who know what is first aid, know how much valuable first aids are, and make time to contribute.

**Pull request merged**
